import type { Migration } from "./types.js";

export const initialSchemaMigration: Migration = {
  id: "001-initial-schema",
  apply(database) {
    database.exec(
      [
        "CREATE TABLE users (",
        "  id TEXT PRIMARY KEY,",
        "  external_subject TEXT NOT NULL UNIQUE,",
        "  display_name TEXT,",
        "  warehouse_recipient_code TEXT NOT NULL,",
        "  created_at TEXT NOT NULL,",
        "  updated_at TEXT NOT NULL",
        ");",
        "",
        "CREATE TABLE warehouses (",
        "  id TEXT PRIMARY KEY,",
        "  name TEXT NOT NULL,",
        "  recipient_name TEXT NOT NULL,",
        "  phone TEXT NOT NULL,",
        "  address_line TEXT NOT NULL,",
        "  instructions TEXT,",
        "  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),",
        "  created_at TEXT NOT NULL,",
        "  updated_at TEXT NOT NULL",
        ");",
        "",
        "CREATE TABLE addresses (",
        "  id TEXT PRIMARY KEY,",
        "  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,",
        "  recipient_name TEXT NOT NULL,",
        "  phone TEXT NOT NULL,",
        "  postcode TEXT NOT NULL,",
        "  address_line TEXT NOT NULL,",
        "  created_at TEXT NOT NULL,",
        "  updated_at TEXT NOT NULL",
        ");",
        "",
        "CREATE TABLE packages (",
        "  id TEXT PRIMARY KEY,",
        "  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,",
        "  warehouse_id TEXT NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,",
        "  domestic_tracking_number TEXT NOT NULL UNIQUE,",
        "  description TEXT NOT NULL,",
        "  status TEXT NOT NULL CHECK (status IN (",
        "    'DECLARED',",
        "    'INBOUND_TO_WAREHOUSE',",
        "    'ARRIVED_PENDING_MATCH',",
        "    'READY_FOR_SHIPMENT',",
        "    'IN_SHIPMENT',",
        "    'EXCEPTION'",
        "  )),",
        "  arrived_at TEXT,",
        "  weight_g INTEGER CHECK (weight_g IS NULL OR weight_g > 0),",
        "  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),",
        "  created_at TEXT NOT NULL,",
        "  updated_at TEXT NOT NULL",
        ");",
        "",
        "CREATE TABLE shipments (",
        "  id TEXT PRIMARY KEY,",
        "  reference TEXT UNIQUE,",
        "  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,",
        "  warehouse_id TEXT NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT,",
        "  address_id TEXT REFERENCES addresses(id) ON DELETE RESTRICT,",
        "  status TEXT NOT NULL CHECK (status IN (",
        "    'DRAFT',",
        "    'SUBMITTED',",
        "    'WAREHOUSE_PROCESSING',",
        "    'AWAITING_PAYMENT',",
        "    'PAYMENT_PROCESSING',",
        "    'PAID_AWAITING_DISPATCH',",
        "    'DISPATCHED',",
        "    'INTERNATIONAL_TRANSIT',",
        "    'CUSTOMS_CLEARANCE',",
        "    'UK_LAST_MILE',",
        "    'DELIVERED',",
        "    'EXCEPTION',",
        "    'CANCELLED'",
        "  )),",
        "  submitted_at TEXT,",
        "  packing_completed_at TEXT,",
        "  final_chargeable_weight_g INTEGER CHECK (",
        "    final_chargeable_weight_g IS NULL OR final_chargeable_weight_g > 0",
        "  ),",
        "  dispatched_at TEXT,",
        "  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),",
        "  created_at TEXT NOT NULL,",
        "  updated_at TEXT NOT NULL,",
        "  CHECK (status = 'DRAFT' OR reference IS NOT NULL)",
        ");",
        "",
        "CREATE TABLE shipment_packages (",
        "  id TEXT PRIMARY KEY,",
        "  shipment_id TEXT NOT NULL REFERENCES shipments(id) ON DELETE RESTRICT,",
        "  package_id TEXT NOT NULL REFERENCES packages(id) ON DELETE RESTRICT,",
        "  locked_at TEXT NOT NULL,",
        "  released_at TEXT,",
        "  release_reason TEXT,",
        "  created_at TEXT NOT NULL,",
        "  UNIQUE (shipment_id, package_id)",
        ");",
        "",
        "CREATE UNIQUE INDEX shipment_packages_one_active_shipment_per_package",
        "  ON shipment_packages(package_id)",
        "  WHERE released_at IS NULL;",
        "",
        "CREATE TABLE quotes (",
        "  id TEXT PRIMARY KEY,",
        "  shipment_id TEXT NOT NULL UNIQUE REFERENCES shipments(id) ON DELETE RESTRICT,",
        "  final_weight_g INTEGER NOT NULL CHECK (final_weight_g > 0),",
        "  chargeable_weight_g INTEGER NOT NULL CHECK (chargeable_weight_g > 0),",
        "  shipping_fee_minor INTEGER NOT NULL CHECK (shipping_fee_minor >= 0),",
        "  service_fee_minor INTEGER NOT NULL CHECK (service_fee_minor >= 0),",
        "  total_amount_minor INTEGER NOT NULL CHECK (",
        "    total_amount_minor = shipping_fee_minor + service_fee_minor",
        "  ),",
        "  currency TEXT NOT NULL CHECK (length(currency) = 3),",
        "  source TEXT NOT NULL DEFAULT 'MOCK_OPS',",
        "  created_at TEXT NOT NULL",
        ");",
        "",
        "CREATE TRIGGER quotes_are_immutable",
        "  BEFORE UPDATE ON quotes",
        "  BEGIN",
        "    SELECT RAISE(ABORT, 'quote snapshots are immutable');",
        "  END;",
        "",
        "CREATE TABLE payments (",
        "  id TEXT PRIMARY KEY,",
        "  shipment_id TEXT NOT NULL REFERENCES shipments(id) ON DELETE RESTRICT,",
        "  quote_id TEXT NOT NULL REFERENCES quotes(id) ON DELETE RESTRICT,",
        "  amount_minor INTEGER NOT NULL CHECK (amount_minor >= 0),",
        "  currency TEXT NOT NULL CHECK (length(currency) = 3),",
        "  status TEXT NOT NULL CHECK (status IN (",
        "    'PROCESSING',",
        "    'SUCCEEDED',",
        "    'FAILED',",
        "    'UNKNOWN'",
        "  )),",
        "  provider TEXT NOT NULL,",
        "  provider_reference TEXT,",
        "  idempotency_key TEXT NOT NULL UNIQUE,",
        "  created_at TEXT NOT NULL,",
        "  completed_at TEXT",
        ");",
        "",
        "CREATE UNIQUE INDEX payments_one_success_per_shipment",
        "  ON payments(shipment_id)",
        "  WHERE status = 'SUCCEEDED';",
        "",
        "CREATE TABLE tracking_events (",
        "  id TEXT PRIMARY KEY,",
        "  shipment_id TEXT NOT NULL REFERENCES shipments(id) ON DELETE RESTRICT,",
        "  event_type TEXT NOT NULL CHECK (event_type IN (",
        "    'DISPATCHED',",
        "    'INTERNATIONAL_TRANSIT',",
        "    'CUSTOMS_CLEARANCE',",
        "    'UK_LAST_MILE',",
        "    'DELIVERED'",
        "  )),",
        "  display_message TEXT NOT NULL,",
        "  source TEXT NOT NULL DEFAULT 'MOCK_OPS',",
        "  occurred_at TEXT NOT NULL,",
        "  created_at TEXT NOT NULL",
        ");",
        "",
        "CREATE INDEX tracking_events_by_shipment_and_time",
        "  ON tracking_events(shipment_id, occurred_at, created_at);",
        "",
        "CREATE TABLE exceptions (",
        "  id TEXT PRIMARY KEY,",
        "  package_id TEXT REFERENCES packages(id) ON DELETE RESTRICT,",
        "  shipment_id TEXT REFERENCES shipments(id) ON DELETE RESTRICT,",
        "  type TEXT NOT NULL,",
        "  status TEXT NOT NULL CHECK (status IN ('OPEN', 'RESOLVED')),",
        "  title TEXT NOT NULL,",
        "  description TEXT NOT NULL,",
        "  impact TEXT NOT NULL,",
        "  required_action TEXT NOT NULL,",
        "  resume_state TEXT NOT NULL,",
        "  is_blocking INTEGER NOT NULL DEFAULT 1 CHECK (is_blocking IN (0, 1)),",
        "  created_at TEXT NOT NULL,",
        "  updated_at TEXT NOT NULL,",
        "  resolved_at TEXT,",
        "  CHECK ((package_id IS NOT NULL) != (shipment_id IS NOT NULL))",
        ");",
        "",
        "CREATE UNIQUE INDEX exceptions_one_open_blocking_per_package",
        "  ON exceptions(package_id)",
        "  WHERE package_id IS NOT NULL AND status = 'OPEN' AND is_blocking = 1;",
        "",
        "CREATE UNIQUE INDEX exceptions_one_open_blocking_per_shipment",
        "  ON exceptions(shipment_id)",
        "  WHERE shipment_id IS NOT NULL AND status = 'OPEN' AND is_blocking = 1;",
        "",
        "CREATE TABLE audit_logs (",
        "  id TEXT PRIMARY KEY,",
        "  actor_type TEXT NOT NULL,",
        "  actor_id TEXT,",
        "  action TEXT NOT NULL,",
        "  entity_type TEXT NOT NULL,",
        "  entity_id TEXT NOT NULL,",
        "  metadata TEXT,",
        "  created_at TEXT NOT NULL",
        ");",
        "",
        "CREATE INDEX packages_by_user_and_status",
        "  ON packages(user_id, status, updated_at);",
        "",
        "CREATE INDEX shipments_by_user_and_status",
        "  ON shipments(user_id, status, updated_at);",
        "",
        "CREATE INDEX audit_logs_by_entity",
        "  ON audit_logs(entity_type, entity_id, created_at);"
      ].join("\n")
    );
  }
};
