export enum PackageStatus {
  DECLARED = "DECLARED",
  INBOUND_TO_WAREHOUSE = "INBOUND_TO_WAREHOUSE",
  ARRIVED_PENDING_MATCH = "ARRIVED_PENDING_MATCH",
  READY_FOR_SHIPMENT = "READY_FOR_SHIPMENT",
  IN_SHIPMENT = "IN_SHIPMENT",
  EXCEPTION = "EXCEPTION"
}

export enum ShipmentStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  WAREHOUSE_PROCESSING = "WAREHOUSE_PROCESSING",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  PAYMENT_PROCESSING = "PAYMENT_PROCESSING",
  PAID_AWAITING_DISPATCH = "PAID_AWAITING_DISPATCH",
  DISPATCHED = "DISPATCHED",
  INTERNATIONAL_TRANSIT = "INTERNATIONAL_TRANSIT",
  CUSTOMS_CLEARANCE = "CUSTOMS_CLEARANCE",
  UK_LAST_MILE = "UK_LAST_MILE",
  DELIVERED = "DELIVERED",
  EXCEPTION = "EXCEPTION",
  CANCELLED = "CANCELLED"
}

export enum PaymentStatus {
  PROCESSING = "PROCESSING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  UNKNOWN = "UNKNOWN"
}

export enum ExceptionStatus {
  OPEN = "OPEN",
  RESOLVED = "RESOLVED"
}

export enum TrackingEventType {
  DISPATCHED = "DISPATCHED",
  INTERNATIONAL_TRANSIT = "INTERNATIONAL_TRANSIT",
  CUSTOMS_CLEARANCE = "CUSTOMS_CLEARANCE",
  UK_LAST_MILE = "UK_LAST_MILE",
  DELIVERED = "DELIVERED"
}
